classifier_scale: 4.0
lr_kernel_n_std: 2
num_samples: 100
show_progress: true
timestep_respacing: '1000'

classifier_use_fp16: false
classifier_width: 128
classifier_depth: 2
classifier_attention_resolutions: 32,16,8
classifier_use_scale_shift_norm: true
classifier_resblock_updown: true
classifier_pool: attention

clip_denoised: true
use_ddim: false
latex_name: RePaint
method_name: Repaint
image_size: 256
#model_path: /home/yingying/project/conditional_diffusion/model_logs/ASTER30_tf/ema_0.999_250000.pt
model_path: /home/zhengxiao/project/repaint/model_logs/ema_0.999_150000.pt
#model_path: /home/yingying/project/conditional_diffusion/model_logs/unconditional_logs/ema_0.999_250000.pt
#model_path: /home/yingying/project/conditional_diffusion/model_logs/ASTER_s2/ema_0.999_500000.pt
name: dem_example
inpa_inj_sched_prev: true
n_jobs: 1
print_estimated_vars: true
inpa_inj_sched_prev_cumnoise: false
condition:
  small_size: 85
  large_size: 256
  condition_flag: "sr"    # sr 三通道   tf 单通道

model:
    image_size: 256
    num_channels: 256
    num_res_blocks: 2
    channel_mult: ""
    learn_sigma: True #diffusion中也有使用
    class_cond: false
    use_checkpoint: true

    attention_resolutions: "32,16,8"
    num_heads: 4
    num_head_channels: 64
    num_heads_upsample: -1
    use_scale_shift_norm: true
    dropout: 0.0
    resblock_updown: true
    use_fp16: false
    use_new_attention_order: false
    in_channels: 1
    out_channels: 1
    condition_channels: 3  # 条件图像通道数
    resamp_with_conv: True
    model_flag: 'train'

diffusion:
    diffusion_steps: 1000
    noise_schedule: cosine
    use_kl: false
    predict_xstart: false
    rescale_timesteps: false
    rescale_learned_sigmas: false
    timestep_respacing: "250"

train:
  batch_size: 1
  microbatch: 1
  lr: 0.00002   # 开始是0.00002
  ema_rate: 0.999
  log_interval: 10
  save_interval: 10000
  resume_checkpoint: /home/zhengxiao/project/repaint/model_logs/icesat2_Norway/ema_0.999_030000.pt
  fp16_scale_growth: 1e-3
  schedule_sampler: uniform
  weight_decay: 0.0
  lr_anneal_steps: 0
  save_path: /home/zhengxiao/project/repaint/model_logs/icesat2_Norway/

schedule_jump_params:
  t_T: 250
  n_sample: 1
  jump_length: 10
  jump_n_sample: 10
data:
  return_dataloader: false #训练时设置为false，测试时设置为true

  train:
    gt_path: /home/zhengxiao/project/repaint/dataset/train/icesat2_Norway/Norway_ReferenceDEM10m_tiles/
    refer_path: /home/zhengxiao/project/repaint/dataset/train/icesat2_Norway/stacked_3channel/
    image_size: 256
    deterministic: true
    random_crop: false
    random_flip: false
    augment: false
    return_dict: true
    drop_last: true
    batch_size: 4
    microbatch: 4
    offset: 0
    max_len: 10561
  eval:
    gt_path: /home/zhangbo/project/repaint/dataset/temp_test/img
    mask_path: /home/zhangbo/project/repaint/dataset/temp_test/mask
    refer_path: /home/zhangbo/project/repaint/dataset/temp_test/label
    image_size: 256
    class_cond: false
    deterministic: true
    random_crop: false
    random_flip: false
    return_dict: true
    drop_last: false
    batch_size: 1
    offset: 0
    max_len: 1
    paths:
      records: /home/zhangbo/project/repaint/dataset/temp/records
      srs: /home/zhangbo/project/repaint/dataset/temp/inpainted
      lrs: /home/zhangbo/project/repaint/dataset/temp/gt_masked
      gts: /home/zhangbo/project/repaint/dataset/temp/gt
      gt_keep_masks: /home/zhangbo/project/repaint/dataset/temp/gt_keep_mask

# python train.py --conf_path confs/train.yml
# 在 dist_util.py 25行设置 GPU 编号